<?php

// Host composition root for the imported PHP pipeline.
namespace scpp\compiler;

// Host loads the shared portable helpers; converted source uses their fixed bindings.
require_once dirname(__DIR__, 2) . '/tools/php_portability/runtime/bootstrap.php';

require_once __DIR__ . '/helpers/storage_abstract.php';
require_once __DIR__ . '/helpers/storage.php';
require_once __DIR__ . '/helpers/storage_cursor.php';
require_once __DIR__ . '/helpers/keyed_storage.php';
require_once __DIR__ . '/helpers/key_storage_list.php';
require_once __DIR__ . '/compiler/sync/structures.php';
require_once __DIR__ . '/01_prepare_inputs/structures.php';
require_once __DIR__ . '/01_prepare_inputs/file.php';
require_once __DIR__ . '/01_prepare_inputs/module.php';
require_once __DIR__ . '/02_tokenize/structures.php';
require_once __DIR__ . '/02_tokenize/text.php';
require_once __DIR__ . '/02_tokenize/tokens.php';
require_once __DIR__ . '/03_parse/types/model.php';
require_once __DIR__ . '/03_parse/types/catalog.php';
require_once __DIR__ . '/03_parse/types/register.php';
require_once __DIR__ . '/05_backend/cpp/type_bindings_catalog.php';
require_once __DIR__ . '/compiler/types/structures.php';
require_once __DIR__ . '/03_parse/scopes/candidates.php';
require_once __DIR__ . '/compiler/constants/structures.php';
require_once __DIR__ . '/compiler/types/language.php';
require_once __DIR__ . '/03_parse/scopes/structures.php';
require_once __DIR__ . '/03_parse/scopes/lookup.php';
require_once __DIR__ . '/compiler/constants/language.php';
require_once __DIR__ . '/compiler/types/source.php';
require_once __DIR__ . '/03_parse/structures/structures_kinds.php';
require_once __DIR__ . '/03_parse/structures/abstractions.php';
require_once __DIR__ . '/03_parse/structures/iterators.php';
require_once __DIR__ . '/03_parse/structures/structures.php';
require_once __DIR__ . '/04_analyze/conversions/model.php';
require_once __DIR__ . '/04_analyze/prepare/data/structures.php';
require_once __DIR__ . '/03_parse/structures/structures_specialization.php';
require_once __DIR__ . '/03_parse/syntax.php';
require_once __DIR__ . '/02_tokenize/buffer.php';
require_once __DIR__ . '/03_parse/token_cleanup.php';
require_once __DIR__ . '/03_parse/parser.php';
require_once __DIR__ . '/04_analyze/collect/structures.php';
// Concrete work accessors use collected-role covariance, which PHP checks while loading classes.
require_once __DIR__ . '/04_analyze/prepare/data/work_records.php';
require_once __DIR__ . '/04_analyze/collect/collect.php';
require_once __DIR__ . '/04_analyze/prepare/changes.php';
require_once __DIR__ . '/04_analyze/prepare/worker.php';
require_once __DIR__ . '/04_analyze/prepare/semantics/literals.php';
require_once __DIR__ . '/04_analyze/prepare/cleanup.php';
require_once __DIR__ . '/04_analyze/prepare/semantics/types.php';
require_once __DIR__ . '/04_analyze/conversions/strings.php';
require_once __DIR__ . '/04_analyze/conversions/booleans.php';
require_once __DIR__ . '/04_analyze/conversions/integers.php';
require_once __DIR__ . '/04_analyze/conversions/floating_points.php';
require_once __DIR__ . '/04_analyze/conversions/preparation.php';
require_once __DIR__ . '/04_analyze/operators/model.php';
require_once __DIR__ . '/04_analyze/operators/integers.php';
require_once __DIR__ . '/04_analyze/operators/preparation.php';
require_once __DIR__ . '/04_analyze/prepare/semantics/declarations.php';
require_once __DIR__ . '/04_analyze/prepare/semantics/bodies.php';
require_once __DIR__ . '/04_analyze/prepare/semantics/expressions.php';
require_once __DIR__ . '/04_analyze/prepare/file.php';
require_once __DIR__ . '/05_backend/cpp/structures.php';
require_once __DIR__ . '/05_backend/cpp/types.php';
require_once __DIR__ . '/05_backend/cpp/declarations.php';
require_once __DIR__ . '/05_backend/cpp/generate.php';
require_once __DIR__ . '/05_backend/cpp/syntax.php';
// Parked LLVM preparation and generation remain loaded for regression entrypoints.
require_once __DIR__ . '/05_backend/llvm/structures.php';
require_once __DIR__ . '/05_backend/llvm/legacy_names.php';
require_once __DIR__ . '/05_backend/llvm/legacy_templates.php';
require_once __DIR__ . '/05_backend/llvm/text.php';
require_once __DIR__ . '/05_backend/llvm/names.php';
require_once __DIR__ . '/05_backend/llvm/prepare.php';
require_once __DIR__ . '/05_backend/llvm/structs.php';
require_once __DIR__ . '/05_backend/llvm/expressions.php';
require_once __DIR__ . '/05_backend/llvm/statements.php';
require_once __DIR__ . '/05_backend/llvm/functions.php';
require_once __DIR__ . '/05_backend/llvm/write.php';
require_once __DIR__ . '/05_backend/llvm/generate.php';
require_once __DIR__ . '/06_native/structures.php';
require_once __DIR__ . '/06_native/run.php';
require_once __DIR__ . '/compiler/model.php';
require_once __DIR__ . '/compiler/sources.php';
require_once __DIR__ . '/compiler/lifecycle.php';
require_once __DIR__ . '/compiler/scope_publication.php';
require_once __DIR__ . '/compiler/structures.php';
require_once __DIR__ . '/compiler/work_queue.php';
require_once __DIR__ . '/compiler/sync/sources.php';
require_once __DIR__ . '/compiler/publication.php';
require_once __DIR__ . '/compiler/frontend.php';
require_once __DIR__ . '/compiler/compile.php';
require_once __DIR__ . '/compiler/host_report.php';
