<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|mixed_t|mixed.null|mixed_t|mixed.string.empty|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Mixed equality follows emitted PHP loose comparison semantics for the current runtime values.

$lhs /** mixed */ = null;
$rhs /** mixed */ = "";

var_dump($lhs != $rhs);
