<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|nullable<int_t>|nullable.present.int.nonzero|nullable<int_t>|nullable.present.int.zero|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Nullable equality treats both empty states as equal and otherwise compares present wrapped values.

$lhs /** ?int */ = 7;
$rhs /** ?int */ = 0;

var_dump($lhs != $rhs);
