<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|result_or_false<string_t>|result_or_false.sentinel.false|result_or_false<string_t>|result_or_false.success.string.nonempty_nonzero_nonbool_literal|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: result_or_false equality normalizes the false sentinel distinctly from wrapped payload values.

$lhs /** result_or_false<string> */ = false;
$rhs /** result_or_false<string> */ = "hello";

var_dump($lhs != $rhs);
