<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|mixed_t|mixed.string.bool_true_literal|mixed_t|mixed.hash.nonempty|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Mixed shared-hash to scalar inequality is defined to return true.

$lhs /** mixed */ = "true";
$rhs /** mixed */ = ["k" => 1];

var_dump($lhs != $rhs);
