<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|result_or_bool<string_t>|result_or_bool.success.string.zero_string|result_or_bool<string_t>|result_or_bool.success.string.nonempty_nonzero_nonbool_literal|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: result_or_bool equality distinguishes false and true sentinels from wrapped payload values.

$lhs /** result_or_bool<string> */ = "0";
$rhs /** result_or_bool<string> */ = "hello";

var_dump($lhs != $rhs);
