<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|result<bool_t>|result.failure|result<bool_t>|result.success.bool.false|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Result equality compares matching success payloads and treats matching failure states as equal in the current matrix slice.

$lhs /** result<bool> */ = error;
$rhs /** result<bool> */ = false;

var_dump($lhs != $rhs);
