<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|result_or_bool<int_t>|result_or_bool.sentinel.false|result_or_bool<int_t>|result_or_bool.success.int.nonzero|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: result_or_bool equality distinguishes false and true sentinels from wrapped payload values.

$lhs /** result_or_bool<int> */ = false;
$rhs /** result_or_bool<int> */ = 7;

var_dump($lhs != $rhs);
