<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|nullable<int_t>|nullable.empty|nullable<int_t>|nullable.empty|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Nullable equality treats both empty states as equal and otherwise compares present wrapped values.

$lhs /** ?int */ = null;
$rhs /** ?int */ = null;

var_dump($lhs != $rhs);
