<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|bool_t|bool.false|bool_t|bool.false|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Deterministic equality follows exact same-type scalar comparison in the current runtime surface.

$lhs /** bool */ = false;
$rhs /** bool */ = false;

var_dump($lhs != $rhs);
