<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|nullable<float_t>|nullable.present.float.zero|nullable<float_t>|nullable.present.float.nonzero|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Nullable equality treats both empty states as equal and otherwise compares present wrapped values.

$lhs /** ?float */ = 0.0;
$rhs /** ?float */ = 3.5;

var_dump($lhs != $rhs);
