<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|not_equal|mixed_t|mixed.string.zero_string|mixed_t|mixed.string.bool_true_literal|-|-|-|-|-
// item: not_equal
// test_seed_class: runtime_success
// notes: Mixed equality follows emitted PHP loose comparison semantics for the current runtime values.

$lhs /** mixed */ = "0";
$rhs /** mixed */ = "true";

var_dump($lhs != $rhs);
