<?php
declare(strict_types=1);

// Fixed global authoring names; php is the internal implementation, target the native binding.
return [
	'fs_read_snapshot' => array ( 'php' => 'scpp\\fs_read_snapshot', 'target' => 'scpp_portability_fs_read_snapshot', 'arity' => 3, ),
	'fs_is_windows' => array ( 'php' => 'scpp\\fs_is_windows', 'target' => 'fs_is_windows', 'arity' => 0, ),
	'fs_basename' => array ( 'php' => 'scpp\\fs_basename', 'target' => 'fs_basename', 'arity' => 1, ),
	'fs_dirname' => array ( 'php' => 'scpp\\fs_dirname', 'target' => 'fs_dirname', 'arity' => 1, ),
	'fs_read_text' => array ( 'php' => 'scpp\\fs_read_text', 'target' => 'scpp_portability_fs_read_text', 'arity' => 1, ),
	'fs_require_realpath' => array ( 'php' => 'scpp\\fs_require_realpath', 'target' => 'scpp_portability_fs_require_realpath', 'arity' => 1, ),
	'json_read' => array ( 'php' => 'scpp\\json_read', 'target' => '\\scpp\\json_read', 'arity' => 1, ),
	'sequence_require_strings' => array ( 'php' => 'scpp\\sequence_require_strings', 'target' => 'scpp_portability_sequence_require_strings', 'arity' => 3, ),
	'fs_is_link' => array ( 'php' => 'scpp\\fs_is_link', 'target' => 'fs_is_link', 'arity' => 1, ),
	'fs_is_dir' => array ( 'php' => 'scpp\\fs_is_dir', 'target' => 'fs_is_dir', 'arity' => 1, ),
	'fs_is_file' => array ( 'php' => 'scpp\\fs_is_file', 'target' => 'fs_is_file', 'arity' => 1, ),
	'fs_size' => array ( 'php' => 'scpp\\fs_size', 'target' => 'scpp_portability_fs_size', 'arity' => 1, ),
	'fs_mtime' => array ( 'php' => 'scpp\\fs_mtime', 'target' => 'scpp_portability_fs_mtime', 'arity' => 1, ),
	'fs_scan' => array ( 'php' => 'scpp\\fs_scan', 'target' => 'scpp_portability_fs_scan', 'arity' => 1, ),
	'json_quote' => array ( 'php' => 'scpp\\json_quote', 'target' => 'scpp_portability_json_quote', 'arity' => 1, ),
	'string_byte_from_int' => array ( 'php' => 'scpp\\string_byte_from_int', 'target' => 'scpp_portability_byte_from_int', 'arity' => 1, ),
	'enum_name' => array ( 'php' => 'scpp\\enum_name', 'target' => 'enum_name', 'arity' => 1, ),
	'lock_empty' => array ( 'php' => 'scpp\\lock_empty', 'target' => 'scpp_portability_lock_empty', 'arity' => 0, ),
	'lock_try' => array ( 'php' => 'scpp\\lock_try', 'target' => 'scpp_portability_lock_try', 'arity' => 3, ),
	'lock_release' => array ( 'php' => 'scpp\\lock_release', 'target' => 'scpp_portability_lock_release', 'arity' => 1, ),
	'lock_transfer' => array ( 'php' => 'scpp\\lock_transfer', 'target' => 'scpp_portability_lock_transfer', 'arity' => 1, ),
	'process_spawn' => array ( 'php' => 'scpp\\process_spawn', 'target' => 'scpp_portability_process_spawn', 'arity' => 5, ),
	'process_poll' => array ( 'php' => 'scpp\\process_poll', 'target' => 'scpp_portability_process_poll', 'arity' => 1, ),
	'process_output' => array ( 'php' => 'scpp\\process_output', 'target' => 'scpp_portability_process_output', 'arity' => 1, ),
	'process_stop' => array ( 'php' => 'scpp\\process_stop', 'target' => 'scpp_portability_process_stop', 'arity' => 1, ),
	'process_close' => array ( 'php' => 'scpp\\process_close', 'target' => 'scpp_portability_process_close', 'arity' => 1, ),
	'sequence_map' => array ( 'php' => 'scpp\\sequence_map', 'target' => 'sequence_map', 'arity' => 2, ),
	'sequence_filter' => array ( 'php' => 'scpp\\sequence_filter', 'target' => 'sequence_filter', 'arity' => 2, ),
	'keyed_map' => array ( 'php' => 'scpp\\keyed_map', 'target' => 'keyed_map', 'arity' => 2, ),
	'keyed_filter' => array ( 'php' => 'scpp\\keyed_filter', 'target' => 'keyed_filter', 'arity' => 2, ),
	'string_byte_len' => array ( 'php' => 'scpp\\string_byte_len', 'target' => 'string_byte_len', 'arity' => 1, ),
	'string_byte_starts_with' => array ( 'php' => 'scpp\\string_byte_starts_with', 'target' => 'str_starts_with', 'arity' => 2, ),
	'string_byte_ends_with' => array ( 'php' => 'scpp\\string_byte_ends_with', 'target' => 'str_ends_with', 'arity' => 2, ),
	'string_utf8_is_valid' => array ( 'php' => 'scpp\\string_utf8_is_valid', 'target' => 'scpp_portability_utf8_valid', 'arity' => 1, ),
	'string_codepoint_at' => array ( 'php' => 'scpp\\string_codepoint_at', 'target' => 'scpp_portability_codepoint_at', 'arity' => 2, ),
	'q_substr' => array ( 'php' => 'scpp\\compat\\substr', 'target' => 'scpp_portability_substr', 'targets' => array ( 2 => 'scpp_portability_substr_to_end', ), 'arity' => array ( 0 => 2, 1 => 3, ), ),
	'q_strpos' => array ( 'php' => 'scpp\\compat\\strpos', 'target' => 'scpp_portability_strpos', 'arity' => array ( 0 => 2, 1 => 3, ), ),
	'q_strrpos' => array ( 'php' => 'scpp\\compat\\strrpos', 'target' => 'scpp_portability_strrpos', 'arity' => array ( 0 => 2, 1 => 3, ), ),
	'same_exception' => array ( 'php' => 'scpp\\same_exception', 'target' => 'scpp_portability_same_exception', 'arity' => 2, ),
	'string_byte_at' => array ( 'php' => 'scpp\\string_byte_at', 'target' => 'string_byte_at', 'arity' => 2, ),
	'q_count' => array ( 'php' => 'count', 'target' => 'count', 'arity' => 1, ),
	'take_nullable' => array ( 'php' => 'scpp\\take_nullable', 'target' => 'take', 'arity' => 2, ),
	'take_false' => array ( 'php' => 'scpp\\take_false', 'target' => 'take', 'arity' => 2, ),
	'take_bool' => array ( 'php' => 'scpp\\take_bool', 'target' => 'take', 'arity' => 3, ),
	'q_is_int' => array ( 'php' => 'is_int', 'target' => 'is_int', 'arity' => 1, ),
	'q_is_bool' => array ( 'php' => 'is_bool', 'target' => 'is_bool', 'arity' => 1, ),
	'q_str_starts_with' => array ( 'php' => 'scpp\\compat\\str_starts_with', 'target' => 'scpp_portability_str_starts_with', 'arity' => 2, ),
	'q_str_ends_with' => array ( 'php' => 'scpp\\compat\\str_ends_with', 'target' => 'scpp_portability_str_ends_with', 'arity' => 2, ),
	'q_strlen' => array ( 'php' => 'scpp\\compat\\strlen', 'target' => 'scpp_portability_strlen', 'arity' => 1, ),
	'string_byte_slice' => array ( 'php' => 'scpp\\string_byte_slice', 'target' => 'string_byte_slice', 'arity' => 3, ),
];
