"""Retained rejection cases plus explicit byte anchors; all expectations independent."""
def cases():
    # text, owner name/kind (empty means entry), anchor, occurrence, diagnostic
    return [
      ('return $missing;','',0,'$missing',0,"Unknown local '$missing'"),
      ('$x = 42;','',0,'$x',0,"Unknown local '$x'"),
      ('$x; $x int = 42;','',0,'$x',0,"Unknown local '$x'"),
      ('{ $hidden int = 42; } return $hidden;','',0,'$hidden',1,"Unknown local '$hidden'"),
      ('$x int = 1; $x int = 2;','',0,'$x',1,"Duplicate local '$x' in this block"),
      ('$x int = $x;','',0,'$x',1,"Local '$x' cannot read itself in its initializer"),
      ('$x int = 1; { $x int = $x; }','',0,'$x',2,"Local '$x' cannot read itself in its initializer"),
      ('$x int = absent();','',0,'absent',0,"Unknown function 'absent'"),
      ('$x int = 1; $x = absent();','',0,'absent',0,"Unknown function 'absent'"),
      ('$X int = 1; return $x;','',0,'$x',0,"Unknown local '$x'"),
      ('$x Missing = 1;','',0,'Missing',0,"Unknown or unsupported local type 'Missing'"),
      ('function bad(): Missing { return 0; }','bad',1,'Missing',0,"Unknown or unsupported return type 'Missing'"),
      ('function bad($x Missing): int { return 0; }','bad',1,'Missing',0,"Unknown or unsupported parameter type 'Missing'"),
      ('struct Box { public Missing $x; }','Box',3,'Missing',0,"Unknown or unsupported field type 'Missing'"),
      ('struct int { public int $x; }','int',3,'int',0,'Duplicate source/provider type: int'),
      ('return MISSING;','',0,'MISSING',0,"Unknown constant or template parameter 'MISSING'"),
      ('const N: int = N;','N',6,'N',1,"Constant 'N' cannot read itself in its initializer"),
      ('{ const N: int = N; }','',0,'N',1,"Constant 'N' cannot read itself in its initializer"),
      ('{ const N: int = 1; const N: int = 2; }','',0,'N',1,"Duplicate or conflicting constant 'N'"),
      ('{ const N: int = 1; } return N;','',0,'N',1,"Unknown constant or template parameter 'N'"),
      ('const N: int = 1; return N();','',0,'N',1,'Calling a constant is not implemented'),
      ('{ const int: int = 1; $x int = 1; }','',0,'int',1,"Constant 'int' is not a type"),
      ('template<typename T> function bad($x T): T { return T; }','bad',5,'T',3,"Template parameter 'T' has the wrong name role"),
      ('template<typename T> function bad($T int): int { return 0; }','bad',5,'$T',0,"Local '$T' conflicts with a template parameter"),
      ('template<typename T> function bad(): int { return T(); }','bad',5,'T',1,'Calling a template parameter is unsupported'),
      ('template<typename T, typename T> struct Bad { public T $x; }','Bad',4,'T',1,"Duplicate or conflicting template parameter 'T'"),
      ('template<typename Bad> struct Bad { public int $x; }','Bad',4,'Bad',0,"Duplicate or conflicting template parameter 'Bad'"),
      ('template<Missing N> struct Bad { public int $x; }','Bad',4,'Missing',0,"Unknown or unsupported template parameter type 'Missing'"),
      ('template<typename T> function identity($x T): T { return $x; } return identity(1);','',0,'identity',1,'Template argument deduction is not implemented; provide explicit arguments'),
      ('template<typename T> struct Box { public T $x; } $x Box<1> = 0;','',0,'1',0,'Expected type argument, not a value expression'),
      ('template<typename T> struct Box { public T $x; } $x Box<int, int> = 0;','',0,'Box<int, int>',0,'Template argument count mismatch'),
      ('$x int = 1; function leak(): int { return $x; }','leak',1,'$x',1,"Unknown local '$x'"),
      ('$x int = 1; if ($x) { $y int = 0; } else { return $y; }','',0,'$y',1,"Unknown local '$y'"),
      ('$x int = 1; while ($x) { $y int = 0; } return $y;','',0,'$y',1,"Unknown local '$y'"),
      ('echo "é"; return $bad;','',0,'$bad',0,"Unknown local '$bad'"),
    ]
