def build():
    cases=[]
    def ok(name,body,ret='int',params='',extra='',statements=1,calls=0,values=1,fall=False):
        cases.append(dict(name=name,source=f'function f({params}): {ret} {{ {body} }} '+extra+' return 0;',error='',statements=statements,calls=calls,values=values,fall=fall))
    def bad(name,body,error,ret='int',params='',extra=''):
        cases.append(dict(name=name,source=f'function f({params}): {ret} {{ {body} }} '+extra+' return 0;',error=error,statements=0,calls=0,values=0,fall=False))
    ok('literal','return 42;')
    ok('parameter','return $x;',params='$x int')
    ok('widen','return $x;',params='$x int32',values=2)
    ok('boolean','return true;',ret='bool')
    ok('addition','return 1 + 2;',values=3)
    ok('less','return 1 < 2;',ret='bool',values=3)
    ok('call','return g(1);',extra='function g($x int): int { return $x; }',calls=1,values=2)
    ok('nested_calls','return g(g(1));',extra='function g($x int): int { return $x; }',calls=2,values=3)
    ok('two_arguments','return g(g(1,2),g(3,4));',extra='function g($x int,$y int): int { return $x; }',calls=3,values=7)
    ok('void_call','g(); return;',ret='void',extra='function g(): void {}',calls=1,values=0,statements=2)
    ok('void_empty','',ret='void',statements=0,values=0,fall=True)
    ok('local_write','$x int = 1; $x = 2; return $x;',statements=3,values=3)
    ok('nested_block','{ $x int = 1; } return 2;',statements=2,values=2)
    ok('both_returns','if (1) { return 2; } else { return 3; }',statements=3,values=3)
    ok('loop','while (1) { 2; } return 3;',statements=3,values=3)
    ok('unused_parameter','$x; return 1;',params='$x int',statements=2,values=2)
    ok('record_default','$p Point; return $p->value;',ret='int32',statements=2,values=2)
    ok('record_construct','$p Point = new Point(); return $p->value;',ret='int32',statements=2,values=2)
    ok('field_write','$p Point; $p->value = $x; return $p->value;',params='$x int32',ret='int32',statements=3,values=3)
    ok('record_copy','$p Point; $q Point = $p; return $q->value;',ret='int32',statements=3,values=3)
    ok('record_assignment','$p Point; $q Point; $q = $p; return $q->value;',ret='int32',statements=4,values=4)
    bad('missing_return','','Callable can finish without returning a value')
    bad('missing_return_arm','if (1) { return 2; }','Callable can finish without returning a value')
    bad('empty_return','return;','A value is required by the declared return type')
    bad('void_return','return 1;','Cannot return a value from a void function',ret='void')
    bad('void_expression_return','return g();','Return expression produces no value',extra='function g(): void {}')
    bad('narrow_return','return 1;','Unsupported implicit return conversion from int to int32',ret='int32')
    bad('arity_missing','return g();','Call argument count does not match the resolved signature',extra='function g($x int): int { return $x; }')
    bad('arity_extra','return g(1,2);','Call argument count does not match the resolved signature',extra='function g($x int): int { return $x; }')
    bad('void_operand','return g() + 1;','Binary operation requires value operands',extra='function g(): void {}')
    bad('mixed_operation','return $x + 1;','Unsupported addition operand types or result contract',params='$x int32')
    bad('const_write','$p->value = $x; return $x;','Cannot write through a const reference parameter',params='const Point &$p, $x int32',ret='int32')
    bad('scalar_default','$x int; return $x;','Default construction requires a supported inline type')
    bad('unknown_field','$p Point; return $p->missing;','Unknown or unavailable field: missing')
    bad('index_scalar','return $x[0];','Indexed access requires a fixed array or typed storage',params='$x int')
    bad('void_condition','if (g()) { return 1; } return 2;','Condition requires an integer value',extra='function g(): void {}')
    bad('literal_overflow','return 9223372036854775808;','Integer literal is outside the range of int')
    bad('byte_no_provider','"abc"; return 1;','No byte-literal construction contract for this context')
    bad('echo_no_provider','echo 1; return 1;','No echo contract for this value type')
    ok('owned_local_return','$p Point; return $p;',ret='Point',statements=2,values=2)
    ok('owned_fresh_return','return new Point();',ret='Point')
    ok('owned_borrow_return','return $p;',ret='Point',params='const Point &$p')
    ok('const_record_call','$p Point; return g($p);',ret='int32',extra='function g(const Point &$p): int32 { return $p->value; }',statements=2,values=3,calls=1)
    ok('mutable_record_call','$p Point; return g($p);',ret='int32',extra='function g(Point &$p): int32 { return $p->value; }',statements=2,values=3,calls=1)
    bad('temporary_record_borrow','return g(new Point());','Record or mutable borrowing requires existing local storage; temporary record borrowing is unsupported',ret='int32',extra='function g(const Point &$p): int32 { return $p->value; }')
    bad('mutable_from_const','return g($p);','A const reference cannot be passed as a mutable reference',params='const Point &$p',ret='int32',extra='function g(Point &$p): int32 { return $p->value; }')
    ok('two_owned_calls','return g() + g();',extra='function g(): int { return 1; }',values=3,calls=2)
    ok('provider_call','return external($x);',ret='int32',params='$x int32',values=2,calls=1)
    ok('array_read','$b Buffer; return $b->data[0];',ret='int32',statements=2,values=3)
    ok('array_write','$b Buffer; $b->data[0] = $x; return $b->data[1];',params='$x int32',ret='int32',statements=3,values=5)
    ok('nested_index','$b Buffer; return $b->data[$b->data[0]];',ret='int32',statements=2,values=4)
    ok('index_call','$b Buffer; return $b->data[g()];',ret='int32',extra='function g(): int { return 0; }',statements=2,values=3,calls=1)
    bad('void_index','$b Buffer; return $b->data[g()];','Array index must be an integer',ret='int32',extra='function g(): void {}')
    ok('deep_addition','return '+' + '.join(['1']*256)+';',values=511)
    ok('deep_calls','return '+'g('*128+'1'+')'*128+';',extra='function g($x int): int { return $x; }',values=129,calls=128)
    ok('deep_blocks','{'*128+'return 1;'+'}'*128)
    # Adapted from retained check_bodies/parameter_bodies.php's explicit plan assertions.
    ok('retained_parameter_plan','$x int = 10; $y int = pair(id($x), id(20)); sink($y); return pair($y, id(42));',extra='function pair($a int,$b int): int { return $a; } function id($v int): int { return $v; } function sink($v int): void { return; }',statements=4,calls=6,values=11)
    ok('named_conversion','return to_byte($x);',params='$x int32',ret='uint8',values=2,calls=1)
    return cases
