<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result<bool_t>|result.failure|result<bool_t>|result.failure|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Result equality compares matching success payloads and treats matching failure states as equal in the current matrix slice.

$lhs /** result<bool> */ = error;
$rhs /** result<bool> */ = error;

var_dump($lhs == $rhs);
