<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result<float_t>|result.success.float.zero|result<float_t>|result.success.float.nonzero|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Result equality compares matching success payloads and treats matching failure states as equal in the current matrix slice.

$lhs /** result<float> */ = 0.0;
$rhs /** result<float> */ = 3.5;

var_dump($lhs == $rhs);
