<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|mixed_t|mixed.string.bool_true_literal|mixed_t|mixed.hash.empty|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Mixed shared-hash to scalar equality is defined to return false.

$lhs /** mixed */ = "true";
$rhs /** mixed */ = [];

var_dump($lhs == $rhs);
