<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result_or_false<int_t>|result_or_false.sentinel.false|result_or_false<int_t>|result_or_false.sentinel.false|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: result_or_false equality normalizes the false sentinel distinctly from wrapped payload values.

$lhs /** result_or_false<int> */ = false;
$rhs /** result_or_false<int> */ = false;

var_dump($lhs == $rhs);
