<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result<string_t>|result.success.string.empty|result<string_t>|result.success.string.bool_false_literal|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Result equality compares matching success payloads and treats matching failure states as equal in the current matrix slice.

$lhs /** result<string> */ = "";
$rhs /** result<string> */ = "false";

var_dump($lhs == $rhs);
