<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result_or_bool<string_t>|result_or_bool.success.string.empty|result_or_bool<string_t>|result_or_bool.success.string.zero_string|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: result_or_bool equality distinguishes false and true sentinels from wrapped payload values.

$lhs /** result_or_bool<string> */ = "";
$rhs /** result_or_bool<string> */ = "0";

var_dump($lhs == $rhs);
