<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|string_t|string.zero_string|string_t|string.empty|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Deterministic equality follows exact same-type scalar comparison in the current runtime surface.

$lhs /** string */ = "0";
$rhs /** string */ = "";

var_dump($lhs == $rhs);
