<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|nullable<string_t>|nullable.present.string.bool_true_literal|nullable<string_t>|nullable.present.string.nonempty_nonzero_nonbool_literal|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Nullable equality treats both empty states as equal and otherwise compares present wrapped values.

$lhs /** ?string */ = "true";
$rhs /** ?string */ = "hello";

var_dump($lhs == $rhs);
