<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|int_t|int.zero|int_t|int.nonzero|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Deterministic equality follows exact same-type scalar comparison in the current runtime surface.

$lhs /** int */ = 0;
$rhs /** int */ = 7;

var_dump($lhs == $rhs);
