<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result<int_t>|result.success.int.zero|result<int_t>|result.failure|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Result equality compares matching success payloads and treats matching failure states as equal in the current matrix slice.

$lhs /** result<int> */ = 0;
$rhs /** result<int> */ = error;

var_dump($lhs == $rhs);
