<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|mixed_t|mixed.bool.true|mixed_t|mixed.float.nonzero|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Mixed equality follows emitted PHP loose comparison semantics for the current runtime values.

$lhs /** mixed */ = true;
$rhs /** mixed */ = 3.5;

var_dump($lhs == $rhs);
