<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|bool_t|bool.true|bool_t|bool.true|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Deterministic equality follows exact same-type scalar comparison in the current runtime surface.

$lhs /** bool */ = true;
$rhs /** bool */ = true;

var_dump($lhs == $rhs);
