<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result_or_bool<float_t>|result_or_bool.success.float.zero|result_or_bool<float_t>|result_or_bool.success.float.nonzero|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: result_or_bool equality distinguishes false and true sentinels from wrapped payload values.

$lhs /** result_or_bool<float> */ = 0.0;
$rhs /** result_or_bool<float> */ = 3.5;

var_dump($lhs == $rhs);
