<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|result_or_false<string_t>|result_or_false.success.string.nonempty_nonzero_nonbool_literal|result_or_false<string_t>|result_or_false.success.string.empty|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: result_or_false equality normalizes the false sentinel distinctly from wrapped payload values.

$lhs /** result_or_false<string> */ = "hello";
$rhs /** result_or_false<string> */ = "";

var_dump($lhs == $rhs);
