<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|mixed_t|mixed.float.zero|mixed_t|mixed.hash.nonempty|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Mixed shared-hash to scalar equality is defined to return false.

$lhs /** mixed */ = 0.0;
$rhs /** mixed */ = ["k" => 1];

var_dump($lhs == $rhs);
