<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|float_t|float.zero|float_t|float.nonzero|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Deterministic equality follows exact same-type scalar comparison in the current runtime surface.

$lhs /** float */ = 0.0;
$rhs /** float */ = 3.5;

var_dump($lhs == $rhs);
