<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|mixed_t|mixed.string.empty|mixed_t|mixed.int.nonzero|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Mixed equality follows emitted PHP loose comparison semantics for the current runtime values.

$lhs /** mixed */ = "";
$rhs /** mixed */ = 7;

var_dump($lhs == $rhs);
