<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|nullable<bool_t>|nullable.present.bool.false|nullable<bool_t>|nullable.present.bool.false|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Nullable equality treats both empty states as equal and otherwise compares present wrapped values.

$lhs /** ?bool */ = false;
$rhs /** ?bool */ = false;

var_dump($lhs == $rhs);
