<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|mixed_t|mixed.hash.empty|mixed_t|mixed.string.nonempty_nonzero_nonbool_literal|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Mixed shared-hash to scalar equality is defined to return false.

$lhs /** mixed */ = [];
$rhs /** mixed */ = "hello";

var_dump($lhs == $rhs);
