<?php
declare(strict_types=1);

// Generated by tools/operator_matrix/generator.php.
// seed_id: seed|operators_comparison_equality|equal|nullable<string_t>|nullable.present.string.empty|nullable<string_t>|nullable.present.string.empty|-|-|-|-|-
// item: equal
// test_seed_class: runtime_success
// notes: Nullable equality treats both empty states as equal and otherwise compares present wrapped values.

$lhs /** ?string */ = "";
$rhs /** ?string */ = "";

var_dump($lhs == $rhs);
