<?php

declare(strict_types=1);

use Scpp\S2S\Transpiler;

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: 0');

ob_start();

$__jsonResponseSent = false;

function emitJsonResponse(array $payload, int $statusCode = 200): void
{
	global $__jsonResponseSent;
	$bufferedOutput = ob_get_contents();
	while (ob_get_level() > 0) {
		@ob_end_clean();
	}
	$__jsonResponseSent = true;
	if ($bufferedOutput !== false && $bufferedOutput !== '') {
		if (!isset($payload['error']) || $payload['error'] === '') {
			$payload['error'] = 'Unexpected output before JSON response: ' . trim((string) $bufferedOutput);
		}
	}
	http_response_code($statusCode);
	echo json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
	exit;
}

$response = [
	'ok' => false,
	'error' => '',
	'generator_header_display' => '',
	'generator_source_display' => '',
	'generator_error' => '',
	's2s_generator_output' => '',
	'generator_include_directive' => '',
	'php_output' => '',
	'php_error' => '',
	'php_exit_code' => null,
	'cpp_output' => '',
	'cpp_error' => '',
	'cpp_exit_code' => null,
	'cpp_compile_output' => '',
	'cpp_compile_error' => '',
	'cpp_compile_exit_code' => null,
	'php_ast_json' => '',
	'php_ast_source' => 'php-ast-json',
	'timing_resources' => [],
	'timing_resources_json' => '',
	'debug_json' => '',
];

register_shutdown_function(static function () use (&$response, &$__jsonResponseSent): void {
	if ($__jsonResponseSent) {
		return;
	}

	$lastError = error_get_last();
	$bufferedOutput = ob_get_contents();
	while (ob_get_level() > 0) {
		@ob_end_clean();
	}

	if ($lastError === null && ($bufferedOutput === false || $bufferedOutput === '')) {
		return;
	}

	if ($lastError !== null) {
		$response['error'] = 'Fatal shutdown: ' . ($lastError['message'] ?? 'unknown error');
		$response['generator_error'] = $response['error'];
		$response['generator_header_display'] = $response['error'];
		$response['generator_source_display'] = '';
		http_response_code(500);
	} elseif ($bufferedOutput !== false && trim((string) $bufferedOutput) !== '') {
		$response['error'] = 'Unexpected non-JSON output before shutdown: ' . trim((string) $bufferedOutput);
		$response['generator_error'] = $response['error'];
		$response['generator_header_display'] = $response['error'];
		$response['generator_source_display'] = '';
		http_response_code(500);
	} else {
		$response['error'] = 'Empty JSON response body generated by run.php.';
		http_response_code(500);
	}

	if (!isset($response['timing_resources_json']) || $response['timing_resources_json'] === '') {
		$response['timing_resources_json'] = encodePrettyJson($response['timing_resources'] ?? []);
	}
	if (!isset($response['debug_json']) || $response['debug_json'] === '') {
		$response['debug_json'] = buildDebugJson($response, '', $response['php_ast_json'] ?? '');
	}

	echo json_encode($response, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
});

try {
	$action = (string) ($_GET['action'] ?? '');
	if ($action !== '') {
		handleUtilityAction($action);
		return;
	}

	if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
		throw new RuntimeException('POST required.');
	}

	$data = readJsonRequestBody();

	$phpCode = trim((string) ($data['php_code'] ?? ''));
	$memTestEnabled = (bool) ($data['mem_test_enabled'] ?? false);
	if ($phpCode === '') {
		throw new RuntimeException('PHP code is empty.');
	}

	if (!str_starts_with(ltrim($phpCode), '<?php')) {
		$phpCode = "<?php\n" . $phpCode;
	}

	if (!extension_loaded('ast')) {
		throw new RuntimeException('The php-ast extension is required for this test UI.');
	}

	$repoRoot = realpath(__DIR__ . '/../../');
	if ($repoRoot === false) {
		throw new RuntimeException('Project root not found.');
	}

	require_once $repoRoot . '/bin/bootstrap.php';
	require_once $repoRoot . '/bin/project_services.php';

	$sandboxRoot = getSandboxRootPath();
	ensureSandboxRootExists($sandboxRoot);
	$selectedSandboxPath = (string) ($data['selected_sandbox_path'] ?? '');
	$entrypointRelativePath = resolveUiEntrypointRelativePath($sandboxRoot, $selectedSandboxPath);
	$entrypointAbsolutePath = resolveSandboxPathInsideRoot($sandboxRoot, $entrypointRelativePath, false);
	ensureDirectoryExists(dirname($entrypointAbsolutePath));
	if (file_put_contents($entrypointAbsolutePath, $phpCode) === false) {
		throw new RuntimeException('Failed to save sandbox entrypoint: ' . $entrypointRelativePath);
	}

	$timingResources = [];
	$response['project_root'] = $sandboxRoot;
	$response['project_entrypoint'] = $entrypointRelativePath;

	$projectConfig = find_project_config($sandboxRoot);
	if ($projectConfig === null) {
		$initStage = measureStage(static function () use ($sandboxRoot, $repoRoot): array {
			return runScppCliService($repoRoot, $sandboxRoot, ['init']);
		});
		$initResult = $initStage['result'];
		$timingResources['init_project'] = stageMetricsFromMeasured($initStage, 'scpp init');
		$timingResources['init_project']['exit_code'] = $initResult['exit_code'];
		$timingResources['init_project']['command'] = $initResult['command'];
		$response['project_init_output'] = normalizeCommandOutput((string) $initResult['output']);
		$response['project_init_error'] = trim((string) $initResult['error']);
		if (!$initResult['ok']) {
			throw new RuntimeException(trim((string) $initResult['error']));
		}
		$projectConfig = find_project_config($sandboxRoot);
	}
	if ($projectConfig === null) {
		throw new RuntimeException('Failed to resolve sandbox project config after initialization.');
	}
	$buildConfigPath = prepareUiBuildConfigPath($projectConfig['project_root'], $projectConfig['config_path'], $entrypointRelativePath);
	if ($buildConfigPath !== $projectConfig['config_path']) {
		$overrideConfigJson = file_get_contents($buildConfigPath);
		if (!is_string($overrideConfigJson) || $overrideConfigJson === '') {
			throw new RuntimeException('Failed to read temporary UI build config.');
		}
		if (file_put_contents($projectConfig['config_path'], $overrideConfigJson) === false) {
			throw new RuntimeException('Failed to refresh sandbox prism.json for selected entrypoint.');
		}
		$buildConfigPath = $projectConfig['config_path'];
	}
	$buildConfig = load_project_config($buildConfigPath);
	$timingResources['project_config'] = [
		'label' => 'Project config',
		'config_path' => normalizeConfigPathForUi(relative_path($projectConfig['project_root'], $buildConfigPath)),
		'entrypoint' => normalizeConfigPathForUi((string) ($buildConfig['entrypoint'] ?? 'main.php')),
	];

	$phpPath = $entrypointAbsolutePath;

	$astVersion = max(ast\get_supported_versions());
	$astStage = measureStage(static function () use ($phpCode, $astVersion): array {
		$fixture = [
			'php_version' => PHP_VERSION,
			'php_ast_extension_version' => phpversion('ast'),
			'ast_version_used' => $astVersion,
			'supported_versions' => ast\get_supported_versions(),
			'tokens' => \token_get_all($phpCode),
			'ast' => ast\parse_code($phpCode, $astVersion),
		];

		return [
			'fixture' => $fixture,
			'json' => (string) json_encode($fixture, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR),
		];
	});
	$phpAstJson = $astStage['result']['json'];
	file_put_contents($phpPath . '.json', $phpAstJson);
	$response['php_ast_json'] = $phpAstJson;
	$timingResources['parse_ast'] = stageMetricsFromMeasured($astStage, 'PHP AST parse + tokens');

	$generatorStage = measureStage(static function () use ($phpPath): array {
		$transpiler = new Transpiler();
		$cppFile = $transpiler->transpile($phpPath);
		return ['cpp_file' => $cppFile];
	});
	$cppFile = $generatorStage['result']['cpp_file'];
	$timingResources['create_cpp_code'] = stageMetricsFromMeasured($generatorStage, 'S2S generate C++');

	$headerDisplay = implode("\n", $cppFile->headerLines) . "\n";
	$sourceDisplay = implode("\n", normalizeSourceForUi($cppFile->sourceLines)) . "\n";
	$response['generator_include_directive'] = extractIncludeDirective($sourceDisplay, $headerDisplay);

	$generatorErrors = implode("\n", $cppFile->errors);
	$generatorWarnings = implode("\n", $cppFile->warnings);
	$response['generator_error'] = $generatorErrors;
	$response['s2s_generator_output'] = $generatorWarnings;
	$response['generator_header_display'] = $generatorErrors !== '' ? $generatorErrors : $headerDisplay;
	$response['generator_source_display'] = $generatorErrors !== '' ? '' : $sourceDisplay;

	$phpRun = runCommandMeasured(
		['php', __DIR__."/run_include.php", $phpPath],
		$repoRoot,
		20
	);
	$response['php_output'] = normalizeCommandOutput($phpRun['stdout']);
	$response['php_error'] = buildProcessErrorText('PHP execution', $phpRun);
	$response['php_exit_code'] = $phpRun['exit_code'];
	$timingResources['execute_php'] = externalMetricsFromRun('PHP execute', $phpRun);

	if ($generatorErrors !== '') {
		$response['cpp_compile_output'] = '';
		$response['cpp_compile_error'] = '';
		$response['cpp_compile_exit_code'] = null;
		$response['cpp_output'] = '';
		$response['cpp_error'] = $generatorErrors;
		$response['cpp_exit_code'] = null;
		$timingResources['compile_cpp'] = [
			'label' => 'scpp build',
			'skipped' => true,
			'reason' => 'generator_failed',
		];
		$timingResources['execute_cpp'] = [
			'label' => 'scpp run',
			'skipped' => true,
			'reason' => 'generator_failed',
		];
	} else {
		$buildStage = measureStage(static function () use ($projectConfig, $repoRoot): array {
			return runScppCliService($repoRoot, $projectConfig['project_root'], ['build']);
		});
		$buildResult = $buildStage['result'];
		$response['cpp_compile_output'] = normalizeCommandOutput((string) $buildResult['output']);
		$response['cpp_compile_error'] = trim((string) $buildResult['error']);
		$response['cpp_compile_exit_code'] = $buildResult['exit_code'];
		$compileMetrics = stageMetricsFromMeasured($buildStage, 'scpp build');
		$compileMetrics['exit_code'] = $buildResult['exit_code'];
		$compileMetrics['mode'] = (string) (($buildConfig['build']['mode'] ?? 'debug'));
		$compileMetrics['entrypoint'] = normalizeConfigPathForUi((string) ($buildConfig['entrypoint'] ?? 'main.php'));
		$compileMetrics['command'] = $buildResult['command'];
		$timingResources['compile_cpp'] = $compileMetrics;

		$buildPayload = [
			'project_root' => $projectConfig['project_root'],
			'build_dir' => normalize_path($projectConfig['project_root'] . '/' . normalize_config_path((string) ($buildConfig['build_dir'] ?? '.prism/build'))),
			'output_name' => build_output_name($entrypointAbsolutePath),
			'output_path' => normalize_path(
				$projectConfig['project_root']
				. '/'
				. normalize_config_path((string) ($buildConfig['build_dir'] ?? '.prism/build'))
				. '/'
				. build_output_name($entrypointAbsolutePath)
			),
		];

		if (!$buildResult['ok']) {
			$response['cpp_error'] = $response['cpp_compile_error'];
			$response['cpp_output'] = '';
			$response['cpp_exit_code'] = null;
			$timingResources['execute_cpp'] = [
				'label' => 'scpp run',
				'skipped' => true,
				'reason' => 'build_failed',
			];
		} else {
			$generatedBase = build_generated_base(
				normalize_path($projectConfig['project_root'] . '/' . normalize_config_path((string) ($buildConfig['generated_dir'] ?? '.prism/generated'))),
				normalize_config_path((string) ($buildConfig['entrypoint'] ?? 'main.php'))
			);
			$generatedHeaderPath = $generatedBase . '.hpp';
			$generatedSourcePath = $generatedBase . '.cpp';
			if (is_file($generatedHeaderPath)) {
				$response['generator_header_display'] = (string) file_get_contents($generatedHeaderPath);
			}
			if (is_file($generatedSourcePath)) {
				$generatedSourceText = (string) file_get_contents($generatedSourcePath);
				$generatedSourceLines = preg_split('/\R/', $generatedSourceText) ?: [];
				$response['generator_source_display'] = implode("
", normalizeSourceForUi($generatedSourceLines)) . "
";
			}
			$response['generator_include_directive'] = extractIncludeDirective($response['generator_source_display'], $response['generator_header_display']);

			$runStage = measureStage(static function () use ($projectConfig, $buildPayload): array {
				return scpp_run_binary_service($projectConfig['project_root'], (string) $buildPayload['output_path']);
			});
			$cppRun = $runStage['result'];
			$response['cpp_output'] = normalizeCommandOutput((string) $cppRun['stdout']);
			$response['cpp_error'] = trim((string) $cppRun['stderr']);
			$response['cpp_exit_code'] = $cppRun['exit_code'];
			$executeMetrics = stageMetricsFromMeasured($runStage, 'scpp run');
			$executeMetrics['exit_code'] = $cppRun['exit_code'];
			$executeMetrics['command'] = $cppRun['command'];
			$timingResources['execute_cpp'] = $executeMetrics;
		}
	}

	$response['timing_resources'] = $timingResources;
	$response['timing_resources_json'] = encodePrettyJson($timingResources);
	$response['debug_json'] = buildDebugJson($response, $phpCode, $response['php_ast_json']);
	$response['ok'] = true;
	emitJsonResponse($response);
} catch (Throwable $throwable) {
	$errorText = formatThrowableDetails($throwable);
	$response['error'] = $errorText." | ".$throwable->getFile()." | line=".$throwable->getLine();
	$response['generator_header_display'] = $errorText;
	$response['generator_source_display'] = '';
	$response['generator_error'] = $errorText." | ".$throwable->getFile()." | line=".$throwable->getLine();;
	$response['timing_resources_json'] = encodePrettyJson($response['timing_resources']);
	$response['debug_json'] = buildDebugJson($response, isset($phpCode) ? $phpCode : '', $response['php_ast_json'] ?? '');
	emitJsonResponse($response, 500);
}

function handleUtilityAction(string $action): void
{
	header('Content-Type: application/json; charset=utf-8');
	header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
	header('Pragma: no-cache');
	header('Expires: 0');

	$root = getSandboxRootPath();
	if ($action === 'sandbox_tree') {
		$payload = [
			'ok' => true,
			'root_display' => $root,
			'tree' => buildSandboxTreePayload($root),
		];
		emitJsonResponse($payload);
	}

	if ($action === 'sandbox_file') {
		$relativePath = (string) ($_GET['path'] ?? '');
		$absolutePath = resolveSandboxFilePath($root, $relativePath);
		$payload = [
			'ok' => true,
			'root_display' => $root,
			'path' => normalizeSandboxRelativePath($relativePath),
			'content' => (string) file_get_contents($absolutePath),
		];
		emitJsonResponse($payload);
	}

	$input = readJsonRequestBody();

	if ($action === 'compile_edited_cpp') {
		$payload = compileEditedCppPayload($input);
		emitJsonResponse($payload);
	}

	if ($action === 'sandbox_save_file') {
		$relativePath = (string) ($input['path'] ?? '');
		$absolutePath = resolveSandboxPathInsideRoot($root, $relativePath, false);
		if (!is_file($absolutePath)) {
			throw new RuntimeException('Sandbox file not found: ' . $relativePath);
		}

		$content = (string) ($input['content'] ?? '');
		if (file_put_contents($absolutePath, $content) === false) {
			throw new RuntimeException('Failed to save sandbox file: ' . $relativePath);
		}

		emitJsonResponse([
			'ok' => true,
			'path' => normalizeSandboxRelativePath($relativePath),
			'type' => 'file',
		]);
	}

	if ($action === 'sandbox_create_file') {
		$parentPath = (string) ($input['parent_path'] ?? '');
		$fileName = trim((string) ($input['name'] ?? ''));
		assertSandboxBaseName($fileName, 'file name');
		$parentAbsolutePath = resolveSandboxPathInsideRoot($root, $parentPath, false);
		if (!is_dir($parentAbsolutePath)) {
			throw new RuntimeException('Sandbox directory not found: ' . $parentPath);
		}

		$newRelativePath = joinSandboxRelativePath($parentPath, $fileName);
		$newAbsolutePath = resolveSandboxPathInsideRoot($root, $newRelativePath, false);
		if (file_exists($newAbsolutePath)) {
			throw new RuntimeException('Sandbox entry already exists: ' . $newRelativePath);
		}
		if (file_put_contents($newAbsolutePath, '') === false) {
			throw new RuntimeException('Failed to create sandbox file: ' . $newRelativePath);
		}

		emitJsonResponse([
			'ok' => true,
			'path' => normalizeSandboxRelativePath($newRelativePath),
			'type' => 'file',
		]);
	}

	if ($action === 'sandbox_create_dir') {
		$parentPath = (string) ($input['parent_path'] ?? '');
		$directoryName = trim((string) ($input['name'] ?? ''));
		assertSandboxBaseName($directoryName, 'directory name');
		$parentAbsolutePath = resolveSandboxPathInsideRoot($root, $parentPath, false);
		if (!is_dir($parentAbsolutePath)) {
			throw new RuntimeException('Sandbox directory not found: ' . $parentPath);
		}

		$newRelativePath = joinSandboxRelativePath($parentPath, $directoryName);
		$newAbsolutePath = resolveSandboxPathInsideRoot($root, $newRelativePath, false);
		if (file_exists($newAbsolutePath)) {
			throw new RuntimeException('Sandbox entry already exists: ' . $newRelativePath);
		}
		if (!mkdir($newAbsolutePath, 0777, true) && !is_dir($newAbsolutePath)) {
			throw new RuntimeException('Failed to create sandbox directory: ' . $newRelativePath);
		}

		emitJsonResponse([
			'ok' => true,
			'path' => normalizeSandboxRelativePath($newRelativePath),
			'type' => 'dir',
		]);
	}

	if ($action === 'sandbox_rename') {
		$relativePath = (string) ($input['path'] ?? '');
		$newName = trim((string) ($input['new_name'] ?? ''));
		assertSandboxBaseName($newName, 'new name');
		$absolutePath = resolveSandboxPathInsideRoot($root, $relativePath, false);
		if (!file_exists($absolutePath)) {
			throw new RuntimeException('Sandbox entry not found: ' . $relativePath);
		}

		$parentRelativePath = dirname(normalizeSandboxRelativePath($relativePath));
		if ($parentRelativePath === '.' || $parentRelativePath === DIRECTORY_SEPARATOR) {
			$parentRelativePath = '';
		}
		$newRelativePath = joinSandboxRelativePath($parentRelativePath, $newName);
		$newAbsolutePath = resolveSandboxPathInsideRoot($root, $newRelativePath, false);
		if (file_exists($newAbsolutePath)) {
			throw new RuntimeException('Sandbox entry already exists: ' . $newRelativePath);
		}
		if (!rename($absolutePath, $newAbsolutePath)) {
			throw new RuntimeException('Failed to rename sandbox entry: ' . $relativePath);
		}

		emitJsonResponse([
			'ok' => true,
			'old_path' => normalizeSandboxRelativePath($relativePath),
			'path' => normalizeSandboxRelativePath($newRelativePath),
			'type' => is_dir($newAbsolutePath) ? 'dir' : 'file',
		]);
	}

	if ($action === 'sandbox_delete_file') {
		$relativePath = (string) ($input['path'] ?? '');
		$absolutePath = resolveSandboxPathInsideRoot($root, $relativePath, false);
		if (!is_file($absolutePath)) {
			throw new RuntimeException('Sandbox file not found: ' . $relativePath);
		}
		if (!unlink($absolutePath)) {
			throw new RuntimeException('Failed to delete sandbox file: ' . $relativePath);
		}

		emitJsonResponse([
			'ok' => true,
			'path' => normalizeSandboxRelativePath($relativePath),
			'type' => 'file',
		]);
	}

	if ($action === 'sandbox_delete_dir') {
		$relativePath = (string) ($input['path'] ?? '');
		$normalizedRelativePath = normalizeSandboxRelativePath($relativePath);
		if ($normalizedRelativePath === '') {
			throw new RuntimeException('Refusing to delete the sandbox root directory.');
		}

		$absolutePath = resolveSandboxPathInsideRoot($root, $normalizedRelativePath, false);
		if (!is_dir($absolutePath)) {
			throw new RuntimeException('Sandbox directory not found: ' . $relativePath);
		}
		deleteSandboxDirectory($absolutePath);

		emitJsonResponse([
			'ok' => true,
			'path' => $normalizedRelativePath,
			'type' => 'dir',
		]);
	}

	throw new RuntimeException('Unknown action: ' . $action);
}

function readJsonRequestBody(): array
{
	// Reuse the raw body cached by the front controller when available.
	// This avoids fragile behavior around repeated php://input reads when this
	// script is included through the public_html router.
	$raw = $GLOBALS['__simple_cpp_raw_request_body'] ?? null;
	if (!is_string($raw)) {
		$fallbackRaw = file_get_contents('php://input');
		$raw = ($fallbackRaw === false) ? '' : $fallbackRaw;
	}

	$trimmed = trim($raw);
	if ($trimmed === '') {
		return [];
	}

	$data = json_decode($raw, true);
	if (is_array($data)) {
		return $data;
	}

	// Some broken gateways can expose the JSON payload as a single form key.
	// Accept that as a last-resort compatibility fallback.
	if ($raw === '' && count($_POST) === 1) {
		$firstKey = (string) array_key_first($_POST);
		$fallbackData = json_decode($firstKey, true);
		if (is_array($fallbackData)) {
			return $fallbackData;
		}
	}

	throw new RuntimeException('Invalid JSON request body.');
}

function normalizeSandboxRelativePath(string $relativePath): string
{
	$trimmedPath = trim($relativePath);
	if ($trimmedPath === '') {
		return '';
	}
	if (str_contains($trimmedPath, "\0")) {
		throw new RuntimeException('Sandbox path contains an invalid null byte.');
	}

	$normalized = str_replace('\\', '/', $trimmedPath);
	$parts = [];
	foreach (explode('/', $normalized) as $part) {
		if ($part === '' || $part === '.') {
			continue;
		}
		if ($part === '..') {
			throw new RuntimeException('Sandbox path may not escape the sandbox root: ' . $relativePath);
		}
		$parts[] = $part;
	}

	return implode('/', $parts);
}

function resolveSandboxPathInsideRoot(string $root, string $relativePath, bool $mustExist = true): string
{
	$normalizedRoot = realpath($root);
	if ($normalizedRoot === false || !is_dir($normalizedRoot)) {
		throw new RuntimeException('Sandbox root directory does not exist yet.');
	}

	$normalizedRelativePath = normalizeSandboxRelativePath($relativePath);
	$candidatePath = $normalizedRoot;
	if ($normalizedRelativePath !== '') {
		$candidatePath .= '/' . $normalizedRelativePath;
	}

	if (!$mustExist) {
		return $candidatePath;
	}

	$resolvedPath = realpath($candidatePath);
	if ($resolvedPath === false) {
		throw new RuntimeException('Sandbox entry not found: ' . $relativePath);
	}
	if (!str_starts_with($resolvedPath, $normalizedRoot . DIRECTORY_SEPARATOR) && $resolvedPath !== $normalizedRoot) {
		throw new RuntimeException('Sandbox path escapes the sandbox root: ' . $relativePath);
	}

	return $resolvedPath;
}

function assertSandboxBaseName(string $name, string $label): void
{
	if ($name === '' || $name === '.' || $name === '..') {
		throw new RuntimeException('Invalid ' . $label . '.');
	}
	if (str_contains($name, "\0") || str_contains($name, '/') || str_contains($name, '\\')) {
		throw new RuntimeException('Invalid ' . $label . '.');
	}
}

function joinSandboxRelativePath(string $left, string $right): string
{
	$left = normalizeSandboxRelativePath($left);
	$right = normalizeSandboxRelativePath($right);
	if ($left === '') {
		return $right;
	}
	if ($right === '') {
		return $left;
	}
	return $left . '/' . $right;
}

function deleteSandboxDirectory(string $absolutePath): void
{
	$iterator = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($absolutePath, FilesystemIterator::SKIP_DOTS),
		RecursiveIteratorIterator::CHILD_FIRST
	);
	foreach ($iterator as $fileInfo) {
		$pathname = $fileInfo->getPathname();
		if ($fileInfo->isDir()) {
			if (!rmdir($pathname)) {
				throw new RuntimeException('Failed to delete sandbox directory: ' . $pathname);
			}
			continue;
		}
		if (!unlink($pathname)) {
			throw new RuntimeException('Failed to delete sandbox file: ' . $pathname);
		}
	}
	if (!rmdir($absolutePath)) {
		throw new RuntimeException('Failed to delete sandbox directory: ' . $absolutePath);
	}
}

function ensureSandboxRootExists(string $root): void
{
	if (is_dir($root)) {
		return;
	}
	if (!mkdir($root, 0777, true) && !is_dir($root)) {
		throw new RuntimeException('Failed to create sandbox root: ' . $root);
	}
}

function ensureDirectoryExists(string $directory): void
{
	if (is_dir($directory)) {
		return;
	}
	if (!mkdir($directory, 0777, true) && !is_dir($directory)) {
		throw new RuntimeException('Failed to create directory: ' . $directory);
	}
}

function normalizeConfigPathForUi(string $path): string
{
	return str_replace('\\', '/', $path);
}

function resolveUiEntrypointRelativePath(string $root, string $selectedSandboxPath): string
{
	$selected = normalizeSandboxRelativePath($selectedSandboxPath);
	if ($selected !== '') {
		if (!str_ends_with(strtolower($selected), '.php')) {
			throw new RuntimeException('Run expects a PHP file selection or no selection. Selected: ' . $selected);
		}
		return $selected;
	}

	$project = find_project_config($root);
	if ($project !== null) {
		$config = load_project_config($project['config_path']);
		$entrypoint = normalize_config_path((string) ($config['entrypoint'] ?? 'main.php'));
		if ($entrypoint !== '') {
			return $entrypoint;
		}
	}

	return 'main.php';
}

function prepareUiBuildConfigPath(string $projectRoot, string $configPath, string $entrypointRelativePath): string
{
	$config = load_project_config($configPath);
	$currentEntrypoint = normalize_config_path((string) ($config['entrypoint'] ?? 'main.php'));
	$targetEntrypoint = normalize_config_path($entrypointRelativePath);
	if ($currentEntrypoint === $targetEntrypoint) {
		return $configPath;
	}

	$config['entrypoint'] = $targetEntrypoint;
	$cacheDirRelative = normalize_config_path((string) ($config['cache_dir'] ?? '.prism/cache'));
	$cacheDirAbsolute = normalize_path($projectRoot . '/' . $cacheDirRelative);
	ensureDirectoryExists($cacheDirAbsolute);
	$overridePath = $cacheDirAbsolute . '/ui_run_prism.json';
	$json = json_encode($config, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
	if (!is_string($json) || $json === '') {
		throw new RuntimeException('Failed to encode temporary UI build config.');
	}
	if (file_put_contents($overridePath, $json . PHP_EOL) === false) {
		throw new RuntimeException('Failed to write temporary UI build config.');
	}
	return $overridePath;
}

function getSandboxRootPath(): string
{
	$root = realpath(__DIR__ . '/../../sandbox');
	if ($root === false) {
		return __DIR__ . '/../../sandbox';
	}

	return $root;
}

function buildSandboxTreePayload(string $root): array
{
	return buildSandboxNode($root, '', 0, true);
}

function buildSandboxNode(string $absolutePath, string $relativePath, int $depth, bool $isRoot = false): array
{
	$name = $isRoot ? basename($absolutePath) : basename($relativePath);
	if ($name === '' || $name === '.' || $name === '..') {
		$name = $isRoot ? 'sandbox' : basename($absolutePath);
	}

	if (!is_dir($absolutePath)) {
		return [
			'type' => 'dir',
			'name' => $name,
			'path' => $relativePath,
			'depth' => $depth,
			'children' => [],
		];
	}

	$entries = scandir($absolutePath);
	if ($entries === false) {
		throw new RuntimeException('Failed to read sandbox directory: ' . $absolutePath);
	}

	$directories = [];
	$files = [];
	foreach ($entries as $entry) {
		if ($entry === '.' || $entry === '..') {
			continue;
		}

		$childAbsolutePath = $absolutePath . DIRECTORY_SEPARATOR . $entry;
		$childRelativePath = $relativePath === '' ? $entry : $relativePath . '/' . $entry;
		if (is_dir($childAbsolutePath)) {
			$directories[] = buildSandboxNode($childAbsolutePath, $childRelativePath, $depth + 1);
			continue;
		}

		if (!is_file($childAbsolutePath)) {
			continue;
		}

		$files[] = [
			'type' => 'file',
			'name' => $entry,
			'path' => $childRelativePath,
			'depth' => $depth + 1,
		];
	}

	usort($directories, static fn(array $left, array $right): int => strcmp((string) $left['name'], (string) $right['name']));
	usort($files, static fn(array $left, array $right): int => strcmp((string) $left['name'], (string) $right['name']));

	return [
		'type' => 'dir',
		'name' => $name,
		'path' => $relativePath,
		'depth' => $depth,
		'children' => array_merge($directories, $files),
	];
}

function resolveSandboxFilePath(string $root, string $relativePath): string
{
	$resolvedPath = resolveSandboxPathInsideRoot($root, $relativePath, true);
	if (!is_file($resolvedPath)) {
		throw new RuntimeException('Sandbox file not found: ' . $relativePath);
	}

	return $resolvedPath;
}


function normalizeSourceForUi(array $sourceLines): array
{
	if ($sourceLines === []) {
		return [];
	}

	$normalized = $sourceLines;
	if (preg_match('/^#include\s+"[^"]+\.hpp"$/', $normalized[0]) === 1) {
		$normalized[0] = '#include <scpp/runtime.hpp>';
	}

	return $normalized;
}

function buildNaturalCompileUnit(array $headerLines, array $sourceLines): string
{
	$filteredSourceLines = $sourceLines;
	if ($filteredSourceLines !== [] && preg_match('/^#include\s+"[^"]+\.hpp"$/', $filteredSourceLines[0]) === 1) {
		array_shift($filteredSourceLines);
		if ($filteredSourceLines !== [] && $filteredSourceLines[0] === '') {
			array_shift($filteredSourceLines);
		}
	}

	return implode("\n", array_merge($headerLines, [''], $filteredSourceLines)) . "\n";
}

function getRuntimeSourceFilesForUi(string $projectRoot): array
{
	$runtimeSrcRoot = $projectRoot . '/runtime/include';
	$paths = [];
	$iter = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($runtimeSrcRoot, FilesystemIterator::SKIP_DOTS)
	);
	foreach ($iter as $fileInfo) {
		if (!$fileInfo->isFile()) {
			continue;
		}

		$path = $fileInfo->getPathname();
		$normalized = str_replace('\\', '/', $path);
		if (!str_ends_with($normalized, '.cpp')) {
			continue;
		}
		$basename = basename($normalized);
		if (str_starts_with($basename, 'test_')) {
			continue;
		}
		if (str_contains($normalized, '/scpp/support/') || str_ends_with($normalized, '/fastcgi_main.cpp')) {
			continue;
		}
		$paths[] = $path;
	}

	sort($paths);
	return $paths;
}

function getRuntimeUiMysqliPkgConfig(string $projectRoot): array
{
	static $cache = [];
	$key = realpath($projectRoot) ?: $projectRoot;
	if (isset($cache[$key])) {
		return $cache[$key];
	}

	foreach (["libmariadb", "mariadb", "mysqlclient"] as $packageName) {
		$existsRun = runCommandMeasured(['pkg-config', '--exists', $packageName], $projectRoot, 10);
		if ($existsRun['exit_code'] !== 0) {
			continue;
		}

		$cflagsRun = runCommandMeasured(['pkg-config', '--cflags', $packageName], $projectRoot, 10);
		$libsRun = runCommandMeasured(['pkg-config', '--libs', $packageName], $projectRoot, 10);
		if ($cflagsRun['exit_code'] !== 0 || $libsRun['exit_code'] !== 0) {
			continue;
		}

		$cflags = preg_split('/\s+/', trim($cflagsRun['stdout'])) ?: [];
		$libs = preg_split('/\s+/', trim($libsRun['stdout'])) ?: [];
		$cflags = array_values(array_filter($cflags, static fn (string $value): bool => $value !== ''));
		$libs = array_values(array_filter($libs, static fn (string $value): bool => $value !== ''));

		return $cache[$key] = [
			'enabled' => true,
			'pkg_name' => $packageName,
			'cflags' => $cflags,
			'libs' => $libs,
		];
	}

	return $cache[$key] = [
		'enabled' => false,
		'pkg_name' => '',
		'cflags' => [],
		'libs' => [],
	];
}

function ensureRuntimeArchive(string $projectRoot, bool $memTestEnabled = false): array
{
	$cacheRoot = $projectRoot . '/runtime/build/test_ui_cache';
	$cacheDir = $cacheRoot . '/' . ($memTestEnabled ? 'asan' : 'default');
	if (!is_dir($cacheDir) && !mkdir($cacheDir, 0777, true) && !is_dir($cacheDir)) {
		throw new RuntimeException('Failed to create runtime cache directory.');
	}

	$signature = computeRuntimeCacheSignature($projectRoot, $memTestEnabled);
	$signaturePath = $cacheDir . '/runtime.signature';
	$archivePath = $cacheDir . '/libruntime_test_ui.a';
	$objectsRoot = $cacheDir . '/objects';
	$currentSignature = is_file($signaturePath) ? trim((string) file_get_contents($signaturePath)) : '';

	if ($currentSignature === $signature && is_file($archivePath)) {
		return [
			'status' => 'reused',
			'archive_path' => $archivePath,
		];
	}

	if (is_dir($objectsRoot)) {
		deleteSandboxDirectory($objectsRoot);
	}
	if (!mkdir($objectsRoot, 0777, true) && !is_dir($objectsRoot)) {
		throw new RuntimeException('Failed to create runtime cache objects directory.');
	}

	$sourceFiles = getRuntimeSourceFilesForUi($projectRoot);
	if ($sourceFiles === []) {
		throw new RuntimeException('No runtime source files were found for the test UI archive build.');
	}

	$objectFiles = [];
	foreach ($sourceFiles as $sourcePath) {
		$relative = substr($sourcePath, strlen($projectRoot . '/runtime/include/'));
		$objectPath = $objectsRoot . '/' . preg_replace('/\.cpp$/', '.o', $relative);
		$objectDir = dirname($objectPath);
		if (!is_dir($objectDir) && !mkdir($objectDir, 0777, true) && !is_dir($objectDir)) {
			throw new RuntimeException('Failed to create runtime object directory: ' . $objectDir);
		}

		$compileRun = runCommandMeasured(
			buildRuntimeCompileCommand($projectRoot, $sourcePath, $objectPath, $memTestEnabled),
			$projectRoot,
			60
		);
		if ($compileRun['exit_code'] !== 0) {
			throw new RuntimeException(buildProcessErrorText('C++ runtime cache build', $compileRun));
		}
		$objectFiles[] = $objectPath;
	}

	$archiveCommand = array_merge(['ar', 'rcs', $archivePath], $objectFiles);
	$archiveRun = runCommandMeasured($archiveCommand, $projectRoot, 20);
	if ($archiveRun['exit_code'] !== 0) {
		throw new RuntimeException(buildProcessErrorText('C++ runtime archive build', $archiveRun));
	}

	file_put_contents($signaturePath, $signature . "
");

	return [
		'status' => 'rebuilt',
		'archive_path' => $archivePath,
	];
}

function computeRuntimeCacheSignature(string $projectRoot, bool $memTestEnabled = false): string
{
	$runtimeRoot = $projectRoot . '/runtime';
	$paths = [];
	$iter = new RecursiveIteratorIterator(
		new RecursiveDirectoryIterator($runtimeRoot, FilesystemIterator::SKIP_DOTS)
	);
	foreach ($iter as $fileInfo) {
		if (!$fileInfo->isFile()) {
			continue;
		}
		$path = $fileInfo->getPathname();
		$normalized = str_replace('\\', '/', $path);
		if (
			str_ends_with($normalized, '.hpp')
			|| str_ends_with($normalized, '.cpp')
			|| str_ends_with($normalized, 'CMakeLists.txt')
		) {
			$paths[] = $path;
		}
	}
	usort($paths, static fn (string $left, string $right): int => strcmp($left, $right));

	$hash = hash_init('sha256');
	hash_update($hash, $memTestEnabled ? "asan\n" : "default\n");
	foreach ($paths as $path) {
		$relative = substr($path, strlen($projectRoot) + 1);
		hash_update($hash, $relative . "
");
		$contents = file_get_contents($path);
		if ($contents === false) {
			throw new RuntimeException('Failed to read runtime dependency for cache signature: ' . $relative);
		}
		hash_update($hash, $contents);
		hash_update($hash, "
--file-boundary--
");
	}

	return hash_final($hash);
}


function measureStage(callable $callback): array
{
	$memoryBefore = memory_get_usage(true);
	$peakBefore = memory_get_peak_usage(true);
	$start = microtime(true);
	$result = $callback();
	$end = microtime(true);
	$memoryAfter = memory_get_usage(true);
	$peakAfter = memory_get_peak_usage(true);

	return [
		'result' => $result,
		'wall_ms' => round(($end - $start) * 1000, 3),
		'memory_before_bytes' => $memoryBefore,
		'memory_after_bytes' => $memoryAfter,
		'memory_delta_bytes' => $memoryAfter - $memoryBefore,
		'peak_before_bytes' => $peakBefore,
		'peak_after_bytes' => $peakAfter,
		'peak_delta_bytes' => $peakAfter - $peakBefore,
	];
}

function stageMetricsFromMeasured(array $measured, string $label): array
{
	return [
		'label' => $label,
		'wall_ms' => $measured['wall_ms'],
		'memory_before_bytes' => $measured['memory_before_bytes'],
		'memory_after_bytes' => $measured['memory_after_bytes'],
		'memory_delta_bytes' => $measured['memory_delta_bytes'],
		'peak_before_bytes' => $measured['peak_before_bytes'],
		'peak_after_bytes' => $measured['peak_after_bytes'],
		'peak_delta_bytes' => $measured['peak_delta_bytes'],
	];
}

function runCommandMeasured(array $command, string $workingDirectory, int $timeoutSeconds): array
{
	$descriptorSpec = [
		0 => ['pipe', 'r'],
		1 => ['pipe', 'w'],
		2 => ['pipe', 'w'],
	];

	$timingMarker = '__SCPP_TIME__';
	$timePath = is_file('/usr/bin/time') ? '/usr/bin/time' : null;
	$processCommand = $command;
	if ($timePath !== null) {
		$escapedParts = array_map(static fn (string $part): string => escapeshellarg($part), $command);
		$escapedMarker = escapeshellarg($timingMarker . '{"elapsed_sec":"%e","max_rss_kb":"%M","user_sec":"%U","sys_sec":"%S"}');
		$processCommand = [
			'/bin/sh',
			'-lc',
			'exec ' . escapeshellarg($timePath) . ' -f ' . $escapedMarker . ' ' . implode(' ', $escapedParts),
		];
	}

	$process = proc_open($processCommand, $descriptorSpec, $pipes, $workingDirectory, buildProcessEnvironment());
	if (!is_resource($process)) {
		throw new RuntimeException('Failed to start process: ' . implode(' ', $command));
	}

	fclose($pipes[0]);
	stream_set_blocking($pipes[1], false);
	stream_set_blocking($pipes[2], false);

	$stdout = '';
	$stderr = '';
	$timedOut = false;
	$start = microtime(true);

	while (true) {
		$status = proc_get_status($process);
		$stdout .= stream_get_contents($pipes[1]);
		$stderr .= stream_get_contents($pipes[2]);

		if ($status['running'] === false) {
			break;
		}

		if ((microtime(true) - $start) > $timeoutSeconds) {
			$timedOut = true;
			proc_terminate($process, 9);
			break;
		}

		usleep(50_000);
	}

	$stdout .= stream_get_contents($pipes[1]);
	$stderr .= stream_get_contents($pipes[2]);
	fclose($pipes[1]);
	fclose($pipes[2]);

	$exitCode = proc_close($process);
	$wallMs = round((microtime(true) - $start) * 1000, 3);
	if ($timedOut && $exitCode === 0) {
		$exitCode = 124;
	}

	$parsedMetrics = parseTimeMetrics($stderr, $timingMarker);

	return [
		'stdout' => $stdout,
		'stderr' => $parsedMetrics['stderr'],
		'exit_code' => $exitCode,
		'timed_out' => $timedOut,
		'wall_ms' => $wallMs,
		'user_ms' => secondsStringToMs($parsedMetrics['metrics']['user_sec'] ?? null),
		'sys_ms' => secondsStringToMs($parsedMetrics['metrics']['sys_sec'] ?? null),
		'max_rss_kb' => isset($parsedMetrics['metrics']['max_rss_kb']) ? (int) $parsedMetrics['metrics']['max_rss_kb'] : null,
		'command' => $command,
	];
}

function runScppCliService(string $repoRoot, string $workingDirectory, array $args, int $timeoutSeconds = 20): array
{
	$scriptPath = normalize_path($repoRoot . '/bin/scpp.php');
	if (!is_file($scriptPath)) {
		throw new RuntimeException('scpp CLI entrypoint not found: ' . $scriptPath);
	}

	$command = build_php_script_command($repoRoot, $scriptPath, $args, true);
	$run = runCommandMeasured($command, $workingDirectory, $timeoutSeconds);

	return [
		'ok' => $run['exit_code'] === 0,
		'output' => $run['stdout'],
		'error' => trim((string) $run['stderr']),
		'exit_code' => $run['exit_code'],
		'command' => $run['command'],
	];
}

function parseTimeMetrics(string $stderr, string $marker): array
{
	$cleanStderr = rtrim($stderr, "\n");
	$metrics = [];
	$pattern = '/(?:^|\n)' . preg_quote($marker, '/') . '(\{.*\})$/s';
	if (preg_match($pattern, $cleanStderr, $matches, PREG_OFFSET_CAPTURE) === 1) {
		$json = $matches[1][0];
		$fullMatchOffset = $matches[0][1];
		$decoded = json_decode($json, true);
		if (is_array($decoded)) {
			$metrics = $decoded;
		}
		$cleanStderr = rtrim(substr($cleanStderr, 0, $fullMatchOffset), "\n");
	}

	return [
		'stderr' => $cleanStderr,
		'metrics' => $metrics,
	];
}

function secondsStringToMs(?string $seconds): ?float
{
	if ($seconds === null || $seconds === '') {
		return null;
	}

	return round(((float) $seconds) * 1000, 3);
}

function normalizeCommandOutput(string $stdout): string
{
	return $stdout;
}

function buildProcessErrorText(string $label, array $run): string
{
	$parts = [];
	if ($run['timed_out'] === true) {
		$parts[] = $label . ' timed out.';
	}
	if ($run['exit_code'] !== 0) {
		$parts[] = $label . ' exit code: ' . $run['exit_code'];
	}
	if (trim($run['stderr']) !== '') {
		$parts[] = rtrim($run['stderr']);
	}
	return implode("\n\n", $parts);
}

function externalMetricsFromRun(string $label, array $run): array
{
	return [
		'label' => $label,
		'wall_ms' => $run['wall_ms'],
		'user_ms' => $run['user_ms'],
		'sys_ms' => $run['sys_ms'],
		'max_rss_kb' => $run['max_rss_kb'],
		'exit_code' => $run['exit_code'],
		'timed_out' => $run['timed_out'],
	];
}

function cleanupDirectory(string $path): void
{
	if (!is_dir($path)) {
		return;
	}

	$items = scandir($path);
	if ($items === false) {
		return;
	}

	foreach ($items as $item) {
		if ($item === '.' || $item === '..') {
			continue;
		}
		$child = $path . '/' . $item;
		if (is_dir($child)) {
			cleanupDirectory($child);
			continue;
		}
		@unlink($child);
	}

	@rmdir($path);
}

function buildDebugJson(array $response, string $phpCode, string $phpAstJson): string
{
	$debug = [
		'source_php_code' => $phpCode,
		'php_ast_source' => $response['php_ast_source'],
		'php_ast_json' => $phpAstJson,
		's2s_generator_output' => $response['s2s_generator_output'],
		's2s_generator_error' => buildErrorObjectFromText($response['generator_error']),
		'generated_cpp_code' => [
			'include_directive' => $response['generator_include_directive'],
			'header' => $response['generator_header_display'],
			'source' => $response['generator_source_display'],
		],
		'php_exit_code' => $response['php_exit_code'],
		'cpp_compiler_output' => $response['cpp_compile_output'] !== '' ? $response['cpp_compile_output'] : ($response['cpp_compile_error'] === '' ? 'compile ok' : ''),
		'cpp_compiler_exit_code' => $response['cpp_compile_exit_code'],
		'cpp_compiler_error' => buildErrorObjectFromText($response['cpp_compile_error']),
		'executed_cpp_output' => $response['cpp_output'],
		'cpp_exit_code' => $response['cpp_exit_code'],
		'cpp_execution_error' => buildErrorObjectFromText($response['cpp_error']),
		'php_output' => $response['php_output'],
		'php_error' => buildErrorObjectFromText($response['php_error']),
		'durations_resources' => $response['timing_resources'],
	];

	return encodePrettyJson($debug);
}

function buildErrorObjectFromText(string $text): array
{
	$text = trim($text);
	if ($text === '') {
		return [];
	}

	$object = [
		'message' => '',
		'file' => '',
		'line' => null,
		'trace' => '',
		'raw' => $text,
	];

	$lines = preg_split('/\R/', $text) ?: [];
	$object['message'] = $lines[0] ?? $text;

	if (preg_match('/^File:\s+(.+)$/m', $text, $matches) === 1) {
		$object['file'] = trim($matches[1]);
	}
	if (preg_match('/^Line:\s+(\d+)$/m', $text, $matches) === 1) {
		$object['line'] = (int) $matches[1];
	}
	if (preg_match('/Trace:\R(.*)$/s', $text, $matches) === 1) {
		$object['trace'] = rtrim($matches[1]);
	}

	return $object;
}

function extractIncludeDirective(string $sourceDisplay, string $headerDisplay): string
{
	foreach ([$sourceDisplay, $headerDisplay] as $text) {
		if (preg_match('/^#include\s+.+$/m', $text, $matches) === 1) {
			return $matches[0];
		}
	}

	return '';
}

function buildNaturalCompileUnitFromText(string $headerText, string $sourceText): string
{
	$headerLines = preg_split('/\R/', str_replace("
", "
", $headerText)) ?: [];
	$sourceLines = preg_split('/\R/', str_replace("
", "
", $sourceText)) ?: [];
	return buildNaturalCompileUnit($headerLines, $sourceLines);
}

function compileEditedCppPayload(array $input): array
{
	$response = [
		'ok' => false,
		'generator_header_display' => (string) ($input['cpp_header_code'] ?? ''),
		'generator_source_display' => (string) ($input['cpp_source_code'] ?? ''),
		'cpp_output' => '',
		'cpp_error' => '',
		'cpp_exit_code' => null,
		'cpp_compile_output' => '',
		'cpp_compile_error' => '',
		'cpp_compile_exit_code' => null,
		's2s_generator_output' => '',
		'generator_error' => '',
		'timing_resources' => [],
		'timing_resources_json' => '',
		'debug_json' => '',
		'error' => '',
	];

	$headerText = (string) ($input['cpp_header_code'] ?? '');
	$sourceText = (string) ($input['cpp_source_code'] ?? '');
	$memTestEnabled = (bool) ($input['mem_test_enabled'] ?? false);
	if (trim($headerText) === '' && trim($sourceText) === '') {
		throw new RuntimeException('Edited C++ header/source is empty.');
	}

	$projectRoot = dirname(__DIR__, 2);
	if (!is_dir($projectRoot)) {
		throw new RuntimeException('Project root not found.');
	}

	$tempRoot = sys_get_temp_dir() . '/simplecpp_test_ui_cpp_' . bin2hex(random_bytes(8));
	if (!mkdir($tempRoot, 0777, true) && !is_dir($tempRoot)) {
		throw new RuntimeException('Failed to create temporary directory.');
	}

	try {
		$headerPath = $tempRoot . '/snippet.hpp';
		$sourcePath = $tempRoot . '/snippet.cpp';
		file_put_contents($headerPath, $headerText);
		file_put_contents($sourcePath, $sourceText);

		$runtimeCacheStage = measureStage(static function () use ($projectRoot, $memTestEnabled): array {
			return ensureRuntimeArchive($projectRoot, $memTestEnabled);
		});
		$runtimeArchive = (string) $runtimeCacheStage['result']['archive_path'];
		$runtimeCacheMetrics = stageMetricsFromMeasured($runtimeCacheStage, 'C++ runtime cache');
		$runtimeCacheMetrics['cache_status'] = (string) ($runtimeCacheStage['result']['status'] ?? 'unknown');
		$runtimeCacheMetrics['archive_path'] = $runtimeArchive;
		$runtimeCacheMetrics['mode'] = $memTestEnabled ? 'asan' : 'default';
		$response['timing_resources']['compile_cpp_runtime_cache'] = $runtimeCacheMetrics;

		$compileInputPath = $tempRoot . '/snippet.build.cpp';
		file_put_contents($compileInputPath, buildNaturalCompileUnitFromText($headerText, $sourceText));
		$cppBinaryPath = $tempRoot . '/snippet.out';

		$compileRun = runCommandMeasured(
			buildSampleCompileCommand($projectRoot, $compileInputPath, $runtimeArchive, $cppBinaryPath, $memTestEnabled),
			$tempRoot,
			40
		);
		$response['cpp_compile_output'] = normalizeCommandOutput($compileRun['stdout']);
		$response['cpp_compile_error'] = buildProcessErrorText('C++ compile', $compileRun);
		$response['cpp_compile_exit_code'] = $compileRun['exit_code'];
		$compileMetrics = externalMetricsFromRun('C++ compile', $compileRun);
		$compileMetrics['mode'] = $memTestEnabled ? 'edited_cpp_plus_cached_runtime_archive_asan' : 'edited_cpp_plus_cached_runtime_archive';
		$compileMetrics['mem_test_enabled'] = $memTestEnabled;
		$response['timing_resources']['compile_cpp'] = $compileMetrics;

		if ($compileRun['exit_code'] !== 0) {
			$response['cpp_error'] = $response['cpp_compile_error'];
			$response['timing_resources']['execute_cpp'] = [
				'label' => 'C++ execute',
				'skipped' => true,
				'reason' => 'compile_failed',
			];
		} else {
			$cppRun = runCommandMeasured([$cppBinaryPath], $tempRoot, 20);
			$response['cpp_output'] = normalizeCommandOutput($cppRun['stdout']);
			$response['cpp_error'] = buildProcessErrorText('C++ execution', $cppRun);
			$response['cpp_exit_code'] = $cppRun['exit_code'];
			$response['timing_resources']['execute_cpp'] = externalMetricsFromRun('C++ execute', $cppRun);
		}

		$response['timing_resources_json'] = encodePrettyJson($response['timing_resources']);
		$response['debug_json'] = encodePrettyJson([
			'mode' => 'compile_edited_cpp',
			'mem_test_enabled' => $memTestEnabled,
			'cpp_compile_exit_code' => $response['cpp_compile_exit_code'],
			'cpp_exit_code' => $response['cpp_exit_code'],
			'cpp_compile_error' => $response['cpp_compile_error'],
			'cpp_error' => $response['cpp_error'],
			's2s_generator_output' => '',
			'generator_error' => '',
			'timing_resources' => $response['timing_resources'],
		]);
		$response['ok'] = true;
		return $response;
	} finally {
		}
}

function encodePrettyJson(array $data): string
{
	return (string) json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}

function formatThrowableDetails(Throwable $throwable): string
{
	$parts = [];
	$parts[] = $throwable->getMessage();
	$parts[] = 'File: ' . $throwable->getFile();
	$parts[] = 'Line: ' . $throwable->getLine();
	$parts[] = "Trace:\n" . $throwable->getTraceAsString();

	return implode("\n", $parts);
}

function buildEffectivePath(?string $pathEnv = null): string
{
	$pathEnv = is_string($pathEnv) ? trim($pathEnv) : '';
	$dirs = [];
	if ($pathEnv !== '') {
		$dirs = array_filter(explode(PATH_SEPARATOR, $pathEnv), static fn (string $dir): bool => $dir !== '');
	}
	if (DIRECTORY_SEPARATOR !== '\\') {
		$dirs = array_merge($dirs, [
			'/usr/local/sbin',
			'/usr/local/bin',
			'/usr/sbin',
			'/usr/bin',
			'/sbin',
			'/bin',
			'/usr/games',
			'/usr/local/games',
			'/snap/bin',
		]);
	}
	$normalized = [];
	foreach ($dirs as $dir) {
		$dir = trim($dir);
		if ($dir === '') {
			continue;
		}
		$normalized[] = rtrim($dir, "\/");
	}
	$normalized = array_values(array_unique($normalized));
	return implode(PATH_SEPARATOR, $normalized);
}

function buildProcessEnvironment(array $extra = []): array
{
	$env = [];
	foreach ([getenv(), $_ENV, $_SERVER] as $source) {
		if (!is_array($source)) {
			continue;
		}
		foreach ($source as $key => $value) {
			if (!is_string($key) || $key == '') {
				continue;
			}
			if (is_array($value) || is_object($value) || $value === null) {
				continue;
			}
			$env[$key] = (string) $value;
		}
	}
	foreach ($extra as $key => $value) {
		if (!is_string($key) || $key == '') {
			continue;
		}
		if (is_array($value) || is_object($value) || $value === null) {
			continue;
		}
		$env[$key] = (string) $value;
	}
	$env['PATH'] = buildEffectivePath($env['PATH'] ?? null);
	return $env;
}

function commandExistsOnPath(string $command): bool
{
	$pathEnv = buildEffectivePath(getenv('PATH') === false ? null : (string) getenv('PATH'));
	if ($pathEnv === '') {
		return false;
	}

	$dirs = array_filter(explode(PATH_SEPARATOR, $pathEnv), static fn (string $dir): bool => $dir !== '');
	$extensions = [''];
	if (DIRECTORY_SEPARATOR === '\\') {
		$pathext = getenv('PATHEXT');
		$extensions = $pathext === false || $pathext === ''
			? ['.exe', '.cmd', '.bat', '.com', '']
			: array_merge(explode(';', strtolower((string) $pathext)), ['']);
		$extensions = array_values(array_unique($extensions));
	}

	foreach ($dirs as $dir) {
		$dir = rtrim($dir, "\\/");
		foreach ($extensions as $extension) {
			$candidate = $dir . DIRECTORY_SEPARATOR . $command;
			if ($extension !== '' && !str_ends_with(strtolower($candidate), $extension)) {
				$candidate .= $extension;
			}
			if (is_file($candidate)) {
				return true;
			}
		}
	}

	return false;
}

function withCompilerLauncher(array $command): array
{
	if ($command === [] || !compilerLauncherIsUsable('sccache', (string) $command[0])) {
		return $command;
	}

	array_unshift($command, 'sccache');
	return $command;
}

function compilerLauncherIsUsable(string $launcher, string $compiler): bool
{
	if ($compiler === '' || !commandExistsOnPath($launcher)) {
		return false;
	}

	$descriptor = [
		0 => ['pipe', 'r'],
		1 => ['pipe', 'w'],
		2 => ['pipe', 'w'],
	];
	$process = @proc_open([$launcher, $compiler, '--version'], $descriptor, $pipes, null, buildProcessEnvironment());
	if (!is_resource($process)) {
		return false;
	}

	fclose($pipes[0]);
	stream_get_contents($pipes[1]);
	stream_get_contents($pipes[2]);
	fclose($pipes[1]);
	fclose($pipes[2]);
	$status = proc_close($process);
	return is_int($status) && $status === 0;
}

function buildRuntimeCompileCommand(string $projectRoot, string $sourcePath, string $objectPath, bool $memTestEnabled = false): array
{
	$mysqliConfig = getRuntimeUiMysqliPkgConfig($projectRoot);
	$command = [
		'g++',
		'-std=c++23',
		'-O3',
		'-DSCPP_LANGUAGE_TARGET_PHP=1',
		'-DSCPP_HAS_MYSQLI=' . ($mysqliConfig['enabled'] ? '1' : '0'),
	];

	if ($memTestEnabled) {
		$command[] = '-fsanitize=address';
	}

	$command = array_merge($command, [
		'-c',
		$sourcePath,
		'-I',
		$projectRoot . '/runtime/include',
	], $mysqliConfig['cflags'], [
		'-o',
		$objectPath,
	]);

	return withCompilerLauncher($command);
}

function buildSampleCompileCommand(string $projectRoot, string $compileInputPath, string $runtimeArchive, string $cppBinaryPath, bool $memTestEnabled = false): array
{
	$mysqliConfig = getRuntimeUiMysqliPkgConfig($projectRoot);
	$command = [
		'g++',
		'-std=c++23',
		'-O3',
		'-DSCPP_LANGUAGE_TARGET_PHP=1',
		'-DSCPP_HAS_MYSQLI=' . ($mysqliConfig['enabled'] ? '1' : '0'),
	];

	if ($memTestEnabled) {
		$command[] = '-fsanitize=address';
	}

	$command = array_merge($command, [
		$compileInputPath,
		$runtimeArchive,
		'-I',
		$projectRoot . '/runtime/include',
	]);

	if (!$memTestEnabled) {
		$command[] = '-ljemalloc';
	}

	$command = array_merge($command, $mysqliConfig['libs'], [
		'-o',
		$cppBinaryPath,
	]);

	return withCompilerLauncher($command);
}
